# Generated by Django 6.0.2 on 2026-02-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
