# Generated by Django 5.2.8 on 2026-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_midia"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="midia_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cover_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
